---

# write package config and install required packages

- import_tasks: ../../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.accept_keywords"
        file: "sys-apps-newrelic-sysmond"
        entries:
          - "sys-apps/newrelic-sysmond ~amd64"
    portage_packages:
      - { package: "sys-apps/newrelic-sysmond" }
